language: python
python:
  - "3.13"
install:
  - pip install sphinx==8.2.3
  - pip install black codecov coverage
script:
  - black --check entrypoint.py sphinx_action tests
  - coverage run --omit="*/tests*" -m unittest
after_success:
  - codecov
